class Airplane:
    def __init__(self):
        self.speed = ...
        self.color = ...
        self.model = ...
        self.capacity = ...
        self.country = ...


    def turn_on(self):
        ...

    def turn_off(self):
        ...

    def fly(self):
        ...

class Car:
    def __init__(self):
        self.speed = ...
        self.color = ...
        self.license_plate = ...
        self.model = ...
        self.capacity = ...

    def turn_on(self):
        ...

    def turn_off(self):
        ...

    def boogh(self):
        ...


class Bicycle:
    def __init__(self):
        self.color = ...

        